import { Request, Response, NextFunction } from 'express';
import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';
import ExcelJS from 'exceljs';
import { v2 as cloudinary } from 'cloudinary';
import TransactionModel from '../models/Transaction.model';
import { sendSuccess, sendError } from '../utils/response.utils';
import { AuthenticatedRequest } from '../middleware/auth.middleware';
import { formatINR } from '../utils/format.utils';
import env from '../config/env';

// Create a local reports directory in case Cloudinary is not configured
const LOCAL_REPORTS_DIR = path.join(__dirname, '../../../reports');
if (!fs.existsSync(LOCAL_REPORTS_DIR)) {
  fs.mkdirSync(LOCAL_REPORTS_DIR, { recursive: true });
}

export const generateReport = async (
  req: AuthenticatedRequest,
  res: Response,
  next: NextFunction
): Promise<void | Response> => {
  const userId = req.user?.id;
  const userName = req.user?.name || 'User';
  if (!userId) return sendError(res, 'User session not found', 404);

  const { type, format, startDate, endDate, categories } = req.body;

  try {
    const query: Record<string, any> = {
      userId,
      date: { $gte: new Date(startDate), $lte: new Date(endDate) },
    };

    if (categories && Array.isArray(categories) && categories.length > 0) {
      query.category = { $in: categories };
    }

    const txns = await TransactionModel.find(query).sort({ date: -1 });

    // Calculate aggregations
    const income = txns.filter((t) => t.type === 'income').reduce((sum, t) => sum + t.amount, 0);
    const expenses = txns.filter((t) => t.type === 'expense').reduce((sum, t) => sum + Math.abs(t.amount), 0);
    const net = income - expenses;
    const rate = income > 0 ? (net / income) * 100 : 0;

    const categorySummary: Record<string, number> = {};
    txns
      .filter((t) => t.type === 'expense')
      .forEach((t) => {
        categorySummary[t.category] = (categorySummary[t.category] || 0) + Math.abs(t.amount);
      });

    const fileName = `FinVerse_Report_${type}_${Date.now()}.${format}`;
    const filePath = path.join(LOCAL_REPORTS_DIR, fileName);

    if (format === 'pdf') {
      // 1. Generate PDF
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      // --- COVER PAGE ---
      doc.rect(0, 0, doc.page.width, doc.page.height).fill('#0F0A1C'); // Deep dark bg
      doc.fillColor('#7C3AED').fontSize(36).font('Helvetica-Bold').text('FinVerse AI', 50, 200);
      doc.fillColor('#FFFFFF').fontSize(22).font('Helvetica').text('Financial Statement Report', 50, 250);
      doc.rect(50, 290, 150, 3).fill('#7C3AED');

      doc.fillColor('#94A3B8').fontSize(12).font('Helvetica-Bold').text('PREPARED FOR:', 50, 420);
      doc.fillColor('#FFFFFF').fontSize(14).font('Helvetica').text(userName, 50, 440);

      doc.fillColor('#94A3B8').fontSize(12).font('Helvetica-Bold').text('REPORT PERIOD:', 50, 500);
      doc.fillColor('#FFFFFF').fontSize(14).font('Helvetica').text(`${startDate} to ${endDate}`, 50, 520);

      doc.fillColor('#94A3B8').fontSize(10).font('Helvetica').text('Autogenerated by FinVerse Personal Assistant', 50, 720);

      doc.addPage({ size: 'A4', margin: 50 });

      // --- SUMMARY PAGE ---
      doc.fillColor('#7C3AED').fontSize(18).font('Helvetica-Bold').text('Financial Summary', 50, 50);
      doc.rect(50, 75, 495, 1).fill('#E2E8F0');

      // Metric Blocks
      doc.fillColor('#334155').rect(50, 100, 140, 70).fill();
      doc.fillColor('#FFFFFF').fontSize(10).text('TOTAL INCOME', 65, 115);
      doc.fontSize(14).font('Helvetica-Bold').fillColor('#10B981').text(formatINR(income), 65, 135);

      doc.fillColor('#334155').rect(205, 100, 140, 70).fill();
      doc.fillColor('#FFFFFF').fontSize(10).font('Helvetica').text('TOTAL EXPENSES', 220, 115);
      doc.fontSize(14).font('Helvetica-Bold').fillColor('#F43F5E').text(formatINR(expenses), 220, 135);

      doc.fillColor('#334155').rect(360, 100, 185, 70).fill();
      doc.fillColor('#FFFFFF').fontSize(10).font('Helvetica').text('NET CASH FLOW', 375, 115);
      doc.fontSize(14).font('Helvetica-Bold').fillColor(net >= 0 ? '#10B981' : '#F43F5E').text(formatINR(net), 375, 135);

      // Category breakdown table
      doc.fillColor('#1E293B').fontSize(14).font('Helvetica-Bold').text('Expense Allocations', 50, 220);
      doc.rect(50, 240, 495, 1).fill('#CBD5E1');

      let yPos = 260;
      doc.fontSize(10).fillColor('#475569');
      doc.text('CATEGORY', 55, yPos);
      doc.text('AMOUNT', 420, yPos);

      Object.entries(categorySummary).forEach(([cat, val]) => {
        yPos += 25;
        doc.fillColor('#334155').fontSize(10).font('Helvetica').text(cat, 55, yPos);
        doc.fillColor('#0F172A').font('Helvetica-Bold').text(formatINR(val), 420, yPos);
      });

      // --- TRANSACTIONS RECORD ---
      doc.addPage();
      doc.fillColor('#7C3AED').fontSize(18).font('Helvetica-Bold').text('Transactions Ledger', 50, 50);
      doc.rect(50, 75, 495, 1).fill('#E2E8F0');

      let tableY = 100;
      doc.fontSize(9).fillColor('#475569');
      doc.text('DATE', 55, tableY);
      doc.text('MERCHANT', 140, tableY);
      doc.text('CATEGORY', 300, tableY);
      doc.text('AMOUNT', 450, tableY);

      txns.slice(0, 20).forEach((t) => {
        tableY += 22;
        if (tableY > 750) {
          doc.addPage();
          tableY = 50;
        }
        doc.fillColor('#0F172A').font('Helvetica').fontSize(9);
        doc.text(t.date.toISOString().split('T')[0], 55, tableY);
        doc.text(t.merchant || t.name, 140, tableY, { width: 150, height: 15, ellipsis: true });
        doc.text(t.category, 300, tableY);
        doc.font('Helvetica-Bold').fillColor(t.type === 'income' ? '#10B981' : '#F43F5E').text(formatINR(Math.abs(t.amount)), 450, tableY);
      });

      doc.end();

      // Wait for stream to write completely
      await new Promise<void>((resolve) => stream.on('finish', () => resolve()));

    } else if (format === 'excel') {
      // 2. Generate Excel Workbook
      const workbook = new ExcelJS.Workbook();
      
      // Sheet 1: Summary info
      const summarySheet = workbook.addWorksheet('Summary');
      summarySheet.columns = [
        { header: 'Metric', key: 'metric', width: 25 },
        { header: 'Value', key: 'value', width: 20 },
      ];
      summarySheet.addRow({ metric: 'Total Income', value: income });
      summarySheet.addRow({ metric: 'Total Expenses', value: expenses });
      summarySheet.addRow({ metric: 'Net Cash Flow', value: net });
      summarySheet.addRow({ metric: 'Savings Rate (%)', value: rate });
      
      summarySheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFF' } };
      summarySheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: '7C3AED' } };

      // Sheet 2: Ledger
      const txnSheet = workbook.addWorksheet('Transactions');
      txnSheet.columns = [
        { header: 'Date', key: 'date', width: 15 },
        { header: 'Merchant', key: 'merchant', width: 25 },
        { header: 'Category', key: 'category', width: 20 },
        { header: 'Type', key: 'type', width: 12 },
        { header: 'Amount (INR)', key: 'amount', width: 15 },
        { header: 'Note', key: 'note', width: 30 },
      ];

      txns.forEach((t) => {
        txnSheet.addRow({
          date: t.date.toISOString().split('T')[0],
          merchant: t.merchant || t.name,
          category: t.category,
          type: t.type,
          amount: Math.abs(t.amount),
          note: t.note,
        });
      });

      txnSheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFF' } };
      txnSheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: '7C3AED' } };

      await workbook.xlsx.writeFile(filePath);

    } else {
      // 3. Generate CSV
      const headers = 'Date,Merchant,Category,Type,Amount,Note\n';
      const rows = txns
        .map((t) => {
          return `"${t.date.toISOString().split('T')[0]}","${t.merchant || t.name}","${t.category}","${t.type}",${Math.abs(t.amount)},"${t.note || ''}"`;
        })
        .join('\n');

      fs.writeFileSync(filePath, headers + rows);
    }

    // Upload to Cloudinary if config keys are set
    const apiKey = env.CLOUDINARY_API_KEY;
    const hasCloudinary = apiKey && apiKey !== 'your-api-key';

    let downloadUrl = '';

    if (hasCloudinary) {
      try {
        const uploadResult = await cloudinary.uploader.upload(filePath, {
          resource_type: 'raw',
          public_id: `reports/${fileName}`,
          overwrite: true,
        });
        downloadUrl = uploadResult.secure_url;
      } catch (err) {
        // Fallback to local link
        downloadUrl = `${env.CLIENT_URL.replace('5173', '5000')}/api/reports/download/${fileName}`;
      }
    } else {
      // Local development link pointing to backend PORT
      downloadUrl = `${env.CLIENT_URL.replace('5173', '5000')}/api/reports/download/${fileName}`;
    }

    return sendSuccess(
      res,
      {
        downloadUrl,
        fileName,
        expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000), // 24 hours expiry
      },
      'Financial statement report compiled successfully'
    );
  } catch (error) {
    next(error);
  }
};

export const downloadReportFile = (req: Request, res: Response): void => {
  const { filename } = req.params;

  // Defense-in-depth: even though the route-level schema validates the filename,
  // we re-check here to prevent path traversal if the middleware is bypassed.
  if (
    !filename ||
    filename.includes('..') ||
    filename.includes('/') ||
    filename.includes('\\')
  ) {
    res.status(400).json({ success: false, message: 'Invalid filename' });
    return;
  }

  const filePath = path.resolve(LOCAL_REPORTS_DIR, path.basename(filename));

  // Ensure the resolved path stays within the reports directory
  if (!filePath.startsWith(path.resolve(LOCAL_REPORTS_DIR))) {
    res.status(403).json({ success: false, message: 'Access denied' });
    return;
  }

  if (fs.existsSync(filePath)) {
    // Determine Content-Type from extension
    const ext = path.extname(filename).toLowerCase();
    const contentTypes: Record<string, string> = {
      '.pdf': 'application/pdf',
      '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      '.csv': 'text/csv',
    };

    res.setHeader('Content-Type', contentTypes[ext] || 'application/octet-stream');
    res.setHeader('Content-Disposition', `attachment; filename="${path.basename(filename)}"`);
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.sendFile(filePath);
  } else {
    res.status(404).json({ success: false, message: 'Requested report file not found or expired' });
  }
};

