import React from 'react';
import { Link } from 'react-router-dom';
import { FileText, ArrowLeft } from 'lucide-react';
import PageTransition from '@/components/common/PageTransition';

export const TermsPage: React.FC = () => {
  return (
    <PageTransition>
      <div className="max-w-4xl mx-auto px-4 py-8 text-white space-y-8">
        <div className="flex items-center justify-between border-b border-white/10 pb-6">
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-[#FF9A6B]/10 border border-[#FF9A6B]/20 text-[#FF9A6B] rounded-lg">
              <FileText size={24} />
            </div>
            <div>
              <h1 className="text-2xl font-bold font-display text-white">Terms & Conditions</h1>
              <p className="text-xs text-white/50">Last updated: [LAST UPDATED DATE]</p>
            </div>
          </div>
          <Link
            to="/"
            className="flex items-center gap-2 text-xs font-semibold px-4 py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg transition-all"
          >
            <ArrowLeft size={14} /> Back to App
          </Link>
        </div>

        <div className="space-y-6 text-sm text-white/80 leading-relaxed">
          <section className="bg-[#2F343C] p-6 border border-white/8 rounded-lg space-y-3">
            <h2 className="text-base font-bold text-white">1. Acceptance of Terms</h2>
            <p>
              By accessing or using FinVerse AI, you agree to comply with and be bound by these Terms and Conditions. If you do not agree with any portion of these terms, you should not access or use the application.
            </p>
          </section>

          <section className="bg-[#2F343C] p-6 border border-white/8 rounded-lg space-y-3">
            <h2 className="text-base font-bold text-white">2. Scope of Service & Non-Financial Advice Disclaimer</h2>
            <p>
              FinVerse AI provides personal financial management tools including manual transaction logging, budget tracking, investment portfolio monitoring, financial report generation, and AI-assisted financial summaries.
            </p>
            <p className="text-xs text-amber-300 font-semibold bg-amber-400/10 p-3 border border-amber-400/20 rounded-lg">
              IMPORTANT: All output, analytics, suggestions, and responses generated by FinVerse AI or its Google Gemini AI Assistant are for informational and educational purposes only. They do NOT constitute professional financial advice, investment recommendations, accounting guidance, or legal counsel. Users are solely responsible for verifying financial calculations and consulting licensed professionals before making investment or financial decisions.
            </p>
          </section>

          <section className="bg-[#2F343C] p-6 border border-white/8 rounded-lg space-y-3">
            <h2 className="text-base font-bold text-white">3. User Responsibilities</h2>
            <ul className="list-disc pl-5 space-y-1 text-xs text-white/70">
              <li>You are responsible for maintaining the confidentiality of your authentication credentials.</li>
              <li>You agree to enter accurate financial records for personal tracking purposes.</li>
              <li>You agree not to use the service for unauthorized, illegal, or fraudulent financial activities.</li>
            </ul>
          </section>

          <section className="bg-[#2F343C] p-6 border border-white/8 rounded-lg space-y-3">
            <h2 className="text-base font-bold text-white">4. Availability & Modifications</h2>
            <p>
              We reserve the right to update, modify, or discontinue features of FinVerse AI at any time. We do not guarantee uninterrupted uptime or error-free processing of third-party API services (such as Firebase or Google Gemini).
            </p>
          </section>

          <section className="bg-[#2F343C] p-6 border border-white/8 rounded-lg space-y-3">
            <h2 className="text-base font-bold text-white">5. Governing Law and Contact</h2>
            <p>
              These Terms and Conditions are governed under [APPLICABLE LAW]. For questions or support requests, contact us at <a href="mailto:[CONTACT EMAIL]" className="text-[#FF9A6B] hover:underline">[CONTACT EMAIL]</a>.
            </p>
          </section>
        </div>
      </div>
    </PageTransition>
  );
};

export default TermsPage;
